package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strconv"
	"strings"
)

func handler(w http.ResponseWriter, r *http.Request) {
	info := strings.Split(strings.Split(r.URL.Path, "/blog/")[1], "+")
	index, err := strconv.Atoi(info[0])
	number, err2 := strconv.Atoi(info[1])

	if err != nil || err2 != nil {
		fmt.Fprintf(w, "Error, input not recognised %q\n", r.URL.Path)
	} else {
		bp := getPosts(index, number)
		js, err := json.Marshal(bp)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		w.Header().Set("Access-Control-Allow-Origin", "*")

		w.Write(js)
	}
}

func main() {
	fmt.Println("Starting")

	args := os.Args[1:]
	if len(args) > 0 {
		if args[0] == "-setup" {
			createDatabase()
		} else if args[0] == "-test" {
			removeDatabase()
			createDatabase()
			openDatabase()
			addPost(blogPost{Post: "Post", Title: "Hello Blog", Author: "Testy McTestface", Timestamp: uint64(4567890)})
			addPost(blogPost{Post: "Post", Title: "Example post 2", Author: "Testy McTestface", Timestamp: uint64(6878)})
			for i := 0; i < 10; i++ {
				addPost(blogPost{Post: fmt.Sprintf("This is %d/10 in the autogenerated posts", 1+i), Title: "Post more posts", Author: "Testy McTestface", Timestamp: uint64(i * 7223243437)})
			}
			fmt.Println(getPosts(1, 2))
		} else if args[0] == "-takedown" {
			removeDatabase()
		}
	} else {
		openDatabase()
		http.HandleFunc("/blog/", handler)
		http.ListenAndServe(":8049", nil)
	}
}
