package main

import (
	"fmt"
	"github.com/jacobrec/spearserver/blog"
	"github.com/jacobrec/spearserver/http"
	"github.com/jacobrec/spearserver/sql"
	"os"
)

func main() {
	fmt.Println("Starting")

	args := os.Args[1:]
	if len(args) > 0 {
		if args[0] == "--setup" {
			sql.CreateDatabase()
		} else if args[0] == "--test" {
			sql.RemoveDatabase()
			sql.CreateDatabase()
			sql.OpenDatabase()
			sql.AddPost(blog.Post{Post: "Post", Title: "Hello Blog", Author: "Testy McTestface", Timestamp: uint64(4567890), Tags: []string{"cool", "first"}})
			sql.AddPost(blog.Post{Post: "Post", Title: "Example post 2", Author: "Testy McTestface", Timestamp: uint64(6878), Tags: []string{"cool", "second"}})
			for i := 0; i < 10; i++ {
				sql.AddPost(blog.Post{Post: fmt.Sprintf("This is %d/10 in the autogenerated posts", 1+i), Title: "Post more posts", Author: "Testy McTestface", Timestamp: uint64(i * 7223243437), Tags: []string{"auto"}})
			}
			fmt.Println(sql.GetPosts(1, 2))
		} else if args[0] == "--takedown" {
			sql.RemoveDatabase()
		}
	} else {
		sql.OpenDatabase()
		http.Begin(":8049")
	}
}
